// <auto-generated />
using System;
using MeetingRoom.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetingRoom.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220100800_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeetingRoom.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserName");

                    b.HasIndex("RoomId", "StartTime", "EndTime");

                    b.ToTable("Reservations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2025, 2, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsCanceled = false,
                            RoomId = 1,
                            StartTime = new DateTime(2025, 2, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "ali@firma.com"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2025, 2, 2, 15, 0, 0, 0, DateTimeKind.Utc),
                            IsCanceled = false,
                            RoomId = 1,
                            StartTime = new DateTime(2025, 2, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "ayse@firma.com"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2025, 2, 3, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsCanceled = false,
                            RoomId = 2,
                            StartTime = new DateTime(2025, 2, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "mehmet@firma.com"
                        });
                });

            modelBuilder.Entity("MeetingRoom.Domain.Entities.ReservationException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExceptionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ReservationSeriesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationSeriesId");

                    b.ToTable("ReservationExceptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExceptionDate = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ReservationSeriesId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExceptionDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ReservationSeriesId = 1
                        });
                });

            modelBuilder.Entity("MeetingRoom.Domain.Entities.ReservationSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Pattern")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ReservationSeries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Haftalık Toplantı",
                            Pattern = "Weekly",
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Aylık Değerlendirme",
                            Pattern = "Monthly",
                            StartDate = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MeetingRoom.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Equipment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 8,
                            Equipment = "Projeksiyon, Beyaz Tahta",
                            Floor = 1,
                            Name = "Toplantı Odası A"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 4,
                            Equipment = "Telefon, TV",
                            Floor = 1,
                            Name = "Toplantı Odası B"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 20,
                            Equipment = "Projeksiyon, Mikrofon, Beyaz Tahta",
                            Floor = 2,
                            Name = "Konferans Salonu"
                        });
                });

            modelBuilder.Entity("MeetingRoom.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("MeetingRoom.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MeetingRoom.Domain.Entities.ReservationException", b =>
                {
                    b.HasOne("MeetingRoom.Domain.Entities.ReservationSeries", null)
                        .WithMany()
                        .HasForeignKey("ReservationSeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
